In [ ]:
#9_1 파일 읽기

with open("dream.txt", "r") as f:
    content = f.read()
    total_characters = len(content)

    words = content.split()
    total_words = len(words)

    total_lines = len(content.split('\n'))

    print(f"총 글자의 수: {total_characters}")
    print(f"총 단어의 수: {total_words}")
    print(f"총 줄의 수: {total_lines}")

In [ ]:
#9_2 파일 쓰기

num = [1, 2, 3, 4, 5]

with open("info", "w") as f:
    sum = 0
    for i in range(len(num)):
        sum += int(num[i])
    f.write(str(sum) + '\n')
    f.write(str(sum / len(num)))

In [ ]:
#9_3 로그 파일 만들기

import os

if not os.path.isdir("log"):
    os.mkdir("log")
if not os.path.exists("log/count_log.txt"):
    f = open("log/count_log.txt", 'w', encoding = "utf8")
    f.write("기록이 시작된다.\n")
    f.close()
with open("log/count_log.txt", 'a', encoding = "utf8") as f:
    import random, datetime
    for i in range(1, 11):
        stamp = str(datetime.datetime.now())
        value = random.random() * 1000000
        log_line = stamp + "\t" + str(value) + "값이 생성되었다." + "\n"
        f.write(log_line)

In [ ]:
#10_1 클래스 구현

class SoccerPlayer(object):
    def __init__(self, name, position, back_number):
        self.name = name
        self.position = position
        self.back_number = back_number

    def change_back_number(self, new_number):
        print("선수 등번호 변경: From %d to %d" %(self.back_number, new_number))
        self.back_number = new_number
        print("현재 선수의 등번호는: %d" %(self.back_number))

player = SoccerPlayer(name="홍길동", position="forward", back_number=9)

new_number = int(input('새로운 선수의 등번호는: '))
player.change_back_number(new_number)

In [ ]:
import matplotlib.pyplot as plt

x = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun']
y = [29, 32, 32, 33, 31, 28, 27]

plt.title('temperature per week')
plt.barh(x, y, color = 'pink')
plt.xlabel('week', fontsize = 10)
plt.ylabel('temperature')
plt.show()

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

print(arr1)
print(arr1.ndim) #배열 열수(차원)
print(arr1.shape) #베열 크기
print(arr1[0])
print(arr1.size) #배열 원소 수
print(type(arr1))

arr1 = np.array([1, 2, 3], ndmin = 2) #2차원 지정
print(arr1)

list1 = [[10, 20, 30], [40, 50, 60]]
arr2 = np.array(list1)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2[0, 0])

In [ ]:
import numpy as np

arr1 = np.zeros((2,3)) #모든 원소 0으로
print(arr1)

arr2 = np.ones((3,4)) #모든 원소 1로
print(arr2)

arr3 = np.eye(3, 3) #대각선 원소 1로, 나머지 0으로
print(arr3)

arr4 = np.full((4,3), 5) #특정 값으로 모든 원소 지정
print(arr4)

arr5 = np.random.randint(1, 10, (3, 4)) #1부터 10까지 난수로 3행 4열 구성
print(arr5)

arr6 = np.linspace(0, 100, num=5, endpoint=True) #간격에 따라서
print(arr6)

In [17]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.append(arr1, 10)
print(arr2)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])
arr3 = np.append(arr1, arr2, axis = 0)  # 행을 기준으로 2차원배열에 추가
print(arr3)

[ 1  2  3  4  5 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
